### ISSUE TITLE
New project doesn't install correctly if created from activated virtualenv

### ISSUE THREAD

**Issue by rszamszur** [rszamszur/fastapi-mvc#37]
- [x] I have searched the [issues](https://github.com/rszamszur/fastapi-mvc/issues) of this repo and believe that this is not a duplicate.

**Describe the bug**
When creating a new project from an activated Poetry shell environment without option `--skip-install`. Executed `make install` in subprocess even though in the different working directory it seems Poetry is not creating a virtual env for a newly created project for some reason.

**Expected behavior**
Even though `fastapi-mvc new` was executed from an activated Poetry shell, the newly created project should install correctly.

**To Reproduce**

Frist activate Poetry shell, and create new project.
```shell
cd fastapi-mvc
make install
potery shell
fastapi-mvc new /tmp/foobar
```
Now from another terminal without activated Poetry shell.
```shell
cd /tmp/foobar/
poetry run foobar serve
```

**Environment**
* Python version: 3.9.9
* Operating System and version: `Linux gdn-n-radoslaws 5.14.18-100.fc33.x86_64 #1 SMP Fri Nov 12 17:38:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* fastapi-mvc version: `commit 5ddece6a9e65bb30f5332bb66ea9d8c8c553d181`

**Additional context**
Example output of the problem
```shell
(.venv) $ fastapi-mvc new /tmp/foobar
[install] Begin installing project.
Updating dependencies
Resolving dependencies... (9.8s)

Writing lock file

No dependencies to install or update

Installing the current project: foobar (0.1.0)
Project successfully installed.
To activate virtualenv run: $ poetry shell
Now you should access CLI script: $ foobar --help
Alternatively you can access CLI script via poetry run: $ poetry run foobar --help
To deactivate virtualenv simply type: $ deactivate
To activate shell completion:
 - for bash: $ echo 'eval "$(_FOOBAR_COMPLETE=source_bash foobar)' >> ~/.bashrc
 - for zsh: $ echo 'eval "$(_FOOBAR_COMPLETE=source_zsh foobar)' >> ~/.zshrc
 - for fish: $ echo 'eval "$(_FOOBAR_COMPLETE=source_fish foobar)' >> ~/.config/fish/completions/foobar.fish
```

Now from another terminal:
```shell
$ cd /tmp/foobar/
$ poetry run foobar serve
Creating virtualenv foobar in /tmp/foobar/.venv
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/tmp/foobar/foobar/cli/cli.py", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

Maybe `subprocess.run(["make", "install"], cwd=app_path)` is executed as child process (hence inherites current virtualenv), and instead it should be fork. My guess is, that `make install` and Poetry looks at the current virtualenv and its dependencies.

**Comment by rszamszur** [comment]
Probably the root cause: https://stackoverflow.com/a/42276825/10566747
> The current environment is always copied to any sub-process (and sub-processes cannot access/change the environment of their parents) 

Maybe `env={}` will solve the problem.

**Comment by rszamszur** [comment]
The `env={}` or `env -i` can solve the problem of inheriting environment variables. However many programs rely on some important environment variables like `HOME`, `PATH`, `PWD` etc. And surely enough:
```shell
$ fastapi-mvc new /tmp/foobar
build/install.sh: line 29: HOME: unbound variable
make: *** [Makefile:27: install] Error 1
```

And running:
```python
subprocess.run(
    ["make", "install"],
    cwd=app_path,
    env={"HOME": os.environ.get("HOME")}
)
```
seems a bit hacky
