### ISSUE TITLE
Migrate to `install-poetry.py` script prior Poetry 1.2.x release migration

### ISSUE THREAD

**Issue by rszamszur** [rszamszur/fastapi-mvc#87]
- [x] I have searched the [issues](https://github.com/rszamszur/fastapi-mvc/issues) of this repo and believe that this is not a duplicate.

## Feature Request

`get-poetry.py` seems to update user PATH by default, which IMHO shouldn't be a default action.
Moreover, migrating to `install-poetry.py` prior #21 can also have additional benefits. 

From Poetry docs:
> Poetry versions installed using the now deprecated `get-poetry.py` installer will not be able to use this command to update to 1.2 releases or later. Migrate to using the `install-poetry.py` installer or `pipx`.

Example of default PATH update with `get-poetry.py`:
```shell
[nix-shell:~/demo]$ fastapi-mvc new galactic-empire
[INFO] Creating a new fastapi-mvc project: galactic-empire
[INFO] Executing shell command: ['make', 'install'].
[install] Poetry is not installed. Begin download and install.
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

$HOME/demo/.poetry/bin

This path will then be added to your `PATH` environment variable by
modifying the profile files located at:

$HOME/.profile
$HOME/.bash_profile

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 1.1.12
  - Downloading poetry-1.1.12-linux.tar.gz (78.78MB)
Traceback (most recent call last):
  File "<stdin>", line 1086, in <module>
  File "<stdin>", line 1082, in main
  File "<stdin>", line 362, in run
  File "<stdin>", line 531, in install
  File "<stdin>", line 737, in update_path
PermissionError: [Errno 13] Permission denied: '/home/rszamszur/.profile'
make: *** [Makefile:27: install] Error 1

```

**Comment by rszamszur** [comment]
+ while at it, update default Poetry to `1.1.13`
